//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSGaryityTool_Win11.Resources.zh_CN {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FSGaryityTool_Win11.Resources.zh_CN.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 亚克力 的本地化字符串。
        /// </summary>
        internal static string _base {
            get {
                return ResourceManager.GetString("base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动连接串口 的本地化字符串。
        /// </summary>
        internal static string autoConnectl {
            get {
                return ResourceManager.GetString("autoConnectl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记忆串口设置 的本地化字符串。
        /// </summary>
        internal static string autoSaveSetl {
            get {
                return ResourceManager.GetString("autoSaveSetl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 接收自动滚动 的本地化字符串。
        /// </summary>
        internal static string autoScrolll {
            get {
                return ResourceManager.GetString("autoScrolll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 热插拔检测 的本地化字符串。
        /// </summary>
        internal static string autoSerichComl {
            get {
                return ResourceManager.GetString("autoSerichComl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置FSGravityTool的背景 的本地化字符串。
        /// </summary>
        internal static string BackgroundDescription {
            get {
                return ResourceManager.GetString("BackgroundDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 波特率 的本地化字符串。
        /// </summary>
        internal static string baudRatel {
            get {
                return ResourceManager.GetString("baudRatel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 要更改连接的设备，您需要重新连接串口。 的本地化字符串。
        /// </summary>
        internal static string comRstInfoBar {
            get {
                return ResourceManager.GetString("comRstInfoBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接设备串口 的本地化字符串。
        /// </summary>
        internal static string connectl {
            get {
                return ResourceManager.GetString("connectl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制本行全部 的本地化字符串。
        /// </summary>
        internal static string copyAlll {
            get {
                return ResourceManager.GetString("copyAlll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制数据 的本地化字符串。
        /// </summary>
        internal static string copyDatal {
            get {
                return ResourceManager.GetString("copyDatal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制时间戳 的本地化字符串。
        /// </summary>
        internal static string copyTimel {
            get {
                return ResourceManager.GetString("copyTimel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据位 的本地化字符串。
        /// </summary>
        internal static string dataBits {
            get {
                return ResourceManager.GetString("dataBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言 Language 的本地化字符串。
        /// </summary>
        internal static string DefLanguage {
            get {
                return ResourceManager.GetString("DefLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择FSGravityTool的显示的语言 的本地化字符串。
        /// </summary>
        internal static string DefLanguageDescription {
            get {
                return ResourceManager.GetString("DefLanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定启动FSGravityTool时显示的页面 的本地化字符串。
        /// </summary>
        internal static string defPageDescription {
            get {
                return ResourceManager.GetString("defPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认起始页 的本地化字符串。
        /// </summary>
        internal static string defStartPage {
            get {
                return ResourceManager.GetString("defStartPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 断开设备串口 的本地化字符串。
        /// </summary>
        internal static string disconnectl {
            get {
                return ResourceManager.GetString("disconnectl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 闪存烧录 的本地化字符串。
        /// </summary>
        internal static string download_Flash {
            get {
                return ResourceManager.GetString("download Flash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 闪存烧录设置 的本地化字符串。
        /// </summary>
        internal static string downloadFlashSettings {
            get {
                return ResourceManager.GetString("downloadFlashSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 串口编码 的本地化字符串。
        /// </summary>
        internal static string encoding {
            get {
                return ResourceManager.GetString("encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 常规 的本地化字符串。
        /// </summary>
        internal static string general {
            get {
                return ResourceManager.GetString("general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 键盘 的本地化字符串。
        /// </summary>
        internal static string keyboard {
            get {
                return ResourceManager.GetString("keyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 键盘驱动设置 的本地化字符串。
        /// </summary>
        internal static string keyboardSettings {
            get {
                return ResourceManager.GetString("keyboardSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用于ESP8266的工具 的本地化字符串。
        /// </summary>
        internal static string mcuToolEsp8266 {
            get {
                return ResourceManager.GetString("mcuToolEsp8266", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用于冰沙主板的工具 的本地化字符串。
        /// </summary>
        internal static string mcuToolLPC1768SMOOTH {
            get {
                return ResourceManager.GetString("mcuToolLPC1768SMOOTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有选择任何工具 的本地化字符串。
        /// </summary>
        internal static string mcuToolNone {
            get {
                return ResourceManager.GetString("mcuToolNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用于RP2040的 MicroPython工具 的本地化字符串。
        /// </summary>
        internal static string mcuToolRP2040MPY {
            get {
                return ResourceManager.GetString("mcuToolRP2040MPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 云母 的本地化字符串。
        /// </summary>
        internal static string mica {
            get {
                return ResourceManager.GetString("mica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 云母替代 的本地化字符串。
        /// </summary>
        internal static string micaAlt {
            get {
                return ResourceManager.GetString("micaAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 鼠标 的本地化字符串。
        /// </summary>
        internal static string mouse {
            get {
                return ResourceManager.GetString("mouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 鼠标驱动设置 的本地化字符串。
        /// </summary>
        internal static string mouseSettings {
            get {
                return ResourceManager.GetString("mouseSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开串口失败，请检查相关设置 的本地化字符串。
        /// </summary>
        internal static string openSPErr {
            get {
                return ResourceManager.GetString("openSPErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开TOML文件 的本地化字符串。
        /// </summary>
        internal static string openToml {
            get {
                return ResourceManager.GetString("openToml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开设置文件 的本地化字符串。
        /// </summary>
        internal static string openTomlDescription {
            get {
                return ResourceManager.GetString("openTomlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索串口完成! 的本地化字符串。
        /// </summary>
        internal static string overSerichSP {
            get {
                return ResourceManager.GetString("overSerichSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 偶校验 的本地化字符串。
        /// </summary>
        internal static string parityEven {
            get {
                return ResourceManager.GetString("parityEven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 奇偶校验 的本地化字符串。
        /// </summary>
        internal static string parityl {
            get {
                return ResourceManager.GetString("parityl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标记校验 的本地化字符串。
        /// </summary>
        internal static string parityMark {
            get {
                return ResourceManager.GetString("parityMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无校验 的本地化字符串。
        /// </summary>
        internal static string parityNone {
            get {
                return ResourceManager.GetString("parityNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 奇校验 的本地化字符串。
        /// </summary>
        internal static string parityOdd {
            get {
                return ResourceManager.GetString("parityOdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 空格校验 的本地化字符串。
        /// </summary>
        internal static string paritySpace {
            get {
                return ResourceManager.GetString("paritySpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 十六进制接收 的本地化字符串。
        /// </summary>
        internal static string rxHexl {
            get {
                return ResourceManager.GetString("rxHexl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 串口绘图器 的本地化字符串。
        /// </summary>
        internal static string serialPlotter {
            get {
                return ResourceManager.GetString("serialPlotter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 串口调试 的本地化字符串。
        /// </summary>
        internal static string serialPort {
            get {
                return ResourceManager.GetString("serialPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 串口 的本地化字符串。
        /// </summary>
        internal static string serialPortl {
            get {
                return ResourceManager.GetString("serialPortl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个性化设置背景 的本地化字符串。
        /// </summary>
        internal static string softToolBackground {
            get {
                return ResourceManager.GetString("softToolBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已关闭 的本地化字符串。
        /// </summary>
        internal static string spClose {
            get {
                return ResourceManager.GetString("spClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已打开 的本地化字符串。
        /// </summary>
        internal static string spConnect {
            get {
                return ResourceManager.GetString("spConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已插入 的本地化字符串。
        /// </summary>
        internal static string spPlogin {
            get {
                return ResourceManager.GetString("spPlogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已拔出 的本地化字符串。
        /// </summary>
        internal static string spPullout {
            get {
                return ResourceManager.GetString("spPullout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 串口调试设置 的本地化字符串。
        /// </summary>
        internal static string spSettings {
            get {
                return ResourceManager.GetString("spSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始搜索串口... 的本地化字符串。
        /// </summary>
        internal static string startSerichSP {
            get {
                return ResourceManager.GetString("startSerichSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止位 的本地化字符串。
        /// </summary>
        internal static string stopBits {
            get {
                return ResourceManager.GetString("stopBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无 的本地化字符串。
        /// </summary>
        internal static string stopNone {
            get {
                return ResourceManager.GetString("stopNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1 的本地化字符串。
        /// </summary>
        internal static string stopOne {
            get {
                return ResourceManager.GetString("stopOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1.5 的本地化字符串。
        /// </summary>
        internal static string stopOnePointFive {
            get {
                return ResourceManager.GetString("stopOnePointFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2 的本地化字符串。
        /// </summary>
        internal static string stopTwo {
            get {
                return ResourceManager.GetString("stopTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 薄亚克力 的本地化字符串。
        /// </summary>
        internal static string thin {
            get {
                return ResourceManager.GetString("thin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入内容不是十六进制数! 的本地化字符串。
        /// </summary>
        internal static string txHexErr {
            get {
                return ResourceManager.GetString("txHexErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 十六进制发送 的本地化字符串。
        /// </summary>
        internal static string txHexl {
            get {
                return ResourceManager.GetString("txHexl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送 的本地化字符串。
        /// </summary>
        internal static string txl {
            get {
                return ResourceManager.GetString("txl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送换行符 的本地化字符串。
        /// </summary>
        internal static string txNewLinel {
            get {
                return ResourceManager.GetString("txNewLinel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 串口字符写入错误! 的本地化字符串。
        /// </summary>
        internal static string txStringErr {
            get {
                return ResourceManager.GetString("txStringErr", resourceCulture);
            }
        }
    }
}
