//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSGaryityTool_Win11.Resources.en_US {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FSGaryityTool_Win11.Resources.en_US.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Connect 的本地化字符串。
        /// </summary>
        internal static string autoConnectl {
            get {
                return ResourceManager.GetString("autoConnectl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto save 的本地化字符串。
        /// </summary>
        internal static string autoSaveSetl {
            get {
                return ResourceManager.GetString("autoSaveSetl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Scroll 的本地化字符串。
        /// </summary>
        internal static string autoScrolll {
            get {
                return ResourceManager.GetString("autoScrolll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hot plug 的本地化字符串。
        /// </summary>
        internal static string autoSerichComl {
            get {
                return ResourceManager.GetString("autoSerichComl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Baudrate 的本地化字符串。
        /// </summary>
        internal static string baudRatel {
            get {
                return ResourceManager.GetString("baudRatel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CONNECT 的本地化字符串。
        /// </summary>
        internal static string connectl {
            get {
                return ResourceManager.GetString("connectl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy all 的本地化字符串。
        /// </summary>
        internal static string copyAlll {
            get {
                return ResourceManager.GetString("copyAlll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy data 的本地化字符串。
        /// </summary>
        internal static string copyDatal {
            get {
                return ResourceManager.GetString("copyDatal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy timestamp 的本地化字符串。
        /// </summary>
        internal static string copyTimel {
            get {
                return ResourceManager.GetString("copyTimel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data bits 的本地化字符串。
        /// </summary>
        internal static string dataBits {
            get {
                return ResourceManager.GetString("dataBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default Starting Page 的本地化字符串。
        /// </summary>
        internal static string defStartPage {
            get {
                return ResourceManager.GetString("defStartPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DISCONNECT 的本地化字符串。
        /// </summary>
        internal static string disconnectl {
            get {
                return ResourceManager.GetString("disconnectl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flash Burn Settings 的本地化字符串。
        /// </summary>
        internal static string downloadFlashSettings {
            get {
                return ResourceManager.GetString("downloadFlashSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General 的本地化字符串。
        /// </summary>
        internal static string general {
            get {
                return ResourceManager.GetString("general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keyboard Settings 的本地化字符串。
        /// </summary>
        internal static string keyboardSettings {
            get {
                return ResourceManager.GetString("keyboardSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mouse Settings 的本地化字符串。
        /// </summary>
        internal static string mouseSettings {
            get {
                return ResourceManager.GetString("mouseSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error connecting to the serial port, please check the parameters! 的本地化字符串。
        /// </summary>
        internal static string openSPErr {
            get {
                return ResourceManager.GetString("openSPErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search SerialPort succeed! 的本地化字符串。
        /// </summary>
        internal static string overSerichSP {
            get {
                return ResourceManager.GetString("overSerichSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parity 的本地化字符串。
        /// </summary>
        internal static string parityl {
            get {
                return ResourceManager.GetString("parityl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hex reception 的本地化字符串。
        /// </summary>
        internal static string rxHexl {
            get {
                return ResourceManager.GetString("rxHexl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Serial Port 的本地化字符串。
        /// </summary>
        internal static string serialPortl {
            get {
                return ResourceManager.GetString("serialPortl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ettings 的本地化字符串。
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 is close 的本地化字符串。
        /// </summary>
        internal static string spClose {
            get {
                return ResourceManager.GetString("spClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 is open 的本地化字符串。
        /// </summary>
        internal static string spConnect {
            get {
                return ResourceManager.GetString("spConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 is plug in 的本地化字符串。
        /// </summary>
        internal static string spPlogin {
            get {
                return ResourceManager.GetString("spPlogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 is pull out 的本地化字符串。
        /// </summary>
        internal static string spPullout {
            get {
                return ResourceManager.GetString("spPullout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Serial Port Settings 的本地化字符串。
        /// </summary>
        internal static string spSettings {
            get {
                return ResourceManager.GetString("spSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start search SerialPort... 的本地化字符串。
        /// </summary>
        internal static string startSerichSP {
            get {
                return ResourceManager.GetString("startSerichSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop bits 的本地化字符串。
        /// </summary>
        internal static string stopBits {
            get {
                return ResourceManager.GetString("stopBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ERROR\r\nThe input is not a hexadecimal number! 的本地化字符串。
        /// </summary>
        internal static string txHexErr {
            get {
                return ResourceManager.GetString("txHexErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hex sending 的本地化字符串。
        /// </summary>
        internal static string txHexl {
            get {
                return ResourceManager.GetString("txHexl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TX 的本地化字符串。
        /// </summary>
        internal static string txl {
            get {
                return ResourceManager.GetString("txl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tx Line Feed 的本地化字符串。
        /// </summary>
        internal static string txNewLinel {
            get {
                return ResourceManager.GetString("txNewLinel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ERROR\r\nSerial port character write error! 的本地化字符串。
        /// </summary>
        internal static string txStringErr {
            get {
                return ResourceManager.GetString("txStringErr", resourceCulture);
            }
        }
    }
}
