//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSGaryityTool_Win11.Resources.en_US {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FSGaryityTool_Win11.Resources.en_US.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Base 的本地化字符串。
        /// </summary>
        internal static string _base {
            get {
                return ResourceManager.GetString("base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default 的本地化字符串。
        /// </summary>
        internal static string _default {
            get {
                return ResourceManager.GetString("default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Connect 的本地化字符串。
        /// </summary>
        internal static string autoConnectl {
            get {
                return ResourceManager.GetString("autoConnectl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto save 的本地化字符串。
        /// </summary>
        internal static string autoSaveSetl {
            get {
                return ResourceManager.GetString("autoSaveSetl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Scroll 的本地化字符串。
        /// </summary>
        internal static string autoScrolll {
            get {
                return ResourceManager.GetString("autoScrolll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hot plug 的本地化字符串。
        /// </summary>
        internal static string autoSerichComl {
            get {
                return ResourceManager.GetString("autoSerichComl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set the background of FSGravityTool. 的本地化字符串。
        /// </summary>
        internal static string BackgroundDescription {
            get {
                return ResourceManager.GetString("BackgroundDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Baudrate 的本地化字符串。
        /// </summary>
        internal static string baudRatel {
            get {
                return ResourceManager.GetString("baudRatel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To change the connected device, you need to reconnect the serial port. 的本地化字符串。
        /// </summary>
        internal static string comRstInfoBar {
            get {
                return ResourceManager.GetString("comRstInfoBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CONNECT 的本地化字符串。
        /// </summary>
        internal static string connectl {
            get {
                return ResourceManager.GetString("connectl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy all 的本地化字符串。
        /// </summary>
        internal static string copyAlll {
            get {
                return ResourceManager.GetString("copyAlll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy data 的本地化字符串。
        /// </summary>
        internal static string copyDatal {
            get {
                return ResourceManager.GetString("copyDatal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy timestamp 的本地化字符串。
        /// </summary>
        internal static string copyTimel {
            get {
                return ResourceManager.GetString("copyTimel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data bits 的本地化字符串。
        /// </summary>
        internal static string dataBits {
            get {
                return ResourceManager.GetString("dataBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Desktop Acrylic 的本地化字符串。
        /// </summary>
        internal static string defaultDesktopAcrylicBackGround {
            get {
                return ResourceManager.GetString("defaultDesktopAcrylicBackGround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 语言 的本地化字符串。
        /// </summary>
        internal static string DefLanguage {
            get {
                return ResourceManager.GetString("DefLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select the language in which FSGravityTool is displayed 的本地化字符串。
        /// </summary>
        internal static string DefLanguageDescription {
            get {
                return ResourceManager.GetString("DefLanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specifies the page that is displayed when FSGravityTool is launched 的本地化字符串。
        /// </summary>
        internal static string defPageDescription {
            get {
                return ResourceManager.GetString("defPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default Starting Page 的本地化字符串。
        /// </summary>
        internal static string defStartPage {
            get {
                return ResourceManager.GetString("defStartPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DISCONNECT 的本地化字符串。
        /// </summary>
        internal static string disconnectl {
            get {
                return ResourceManager.GetString("disconnectl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download Flash 的本地化字符串。
        /// </summary>
        internal static string download_Flash {
            get {
                return ResourceManager.GetString("download Flash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flash Burn Settings 的本地化字符串。
        /// </summary>
        internal static string downloadFlashSettings {
            get {
                return ResourceManager.GetString("downloadFlashSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Encoding 的本地化字符串。
        /// </summary>
        internal static string encoding {
            get {
                return ResourceManager.GetString("encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General 的本地化字符串。
        /// </summary>
        internal static string general {
            get {
                return ResourceManager.GetString("general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keyboard 的本地化字符串。
        /// </summary>
        internal static string keyboard {
            get {
                return ResourceManager.GetString("keyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keyboard Settings 的本地化字符串。
        /// </summary>
        internal static string keyboardSettings {
            get {
                return ResourceManager.GetString("keyboardSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tools for ESP8266 的本地化字符串。
        /// </summary>
        internal static string mcuToolEsp8266 {
            get {
                return ResourceManager.GetString("mcuToolEsp8266", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tools for Smoothieboard 的本地化字符串。
        /// </summary>
        internal static string mcuToolLPC1768SMOOTH {
            get {
                return ResourceManager.GetString("mcuToolLPC1768SMOOTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No tools was selected 的本地化字符串。
        /// </summary>
        internal static string mcuToolNone {
            get {
                return ResourceManager.GetString("mcuToolNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tools for MicroPython in RP2040 的本地化字符串。
        /// </summary>
        internal static string mcuToolRP2040MPY {
            get {
                return ResourceManager.GetString("mcuToolRP2040MPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mica 的本地化字符串。
        /// </summary>
        internal static string mica {
            get {
                return ResourceManager.GetString("mica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mica Alt 的本地化字符串。
        /// </summary>
        internal static string micaAlt {
            get {
                return ResourceManager.GetString("micaAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mouse 的本地化字符串。
        /// </summary>
        internal static string mouse {
            get {
                return ResourceManager.GetString("mouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mouse Settings 的本地化字符串。
        /// </summary>
        internal static string mouseSettings {
            get {
                return ResourceManager.GetString("mouseSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error connecting to the serial port, please check the parameters! 的本地化字符串。
        /// </summary>
        internal static string openSPErr {
            get {
                return ResourceManager.GetString("openSPErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open TOML file 的本地化字符串。
        /// </summary>
        internal static string openToml {
            get {
                return ResourceManager.GetString("openToml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open the settings file. 的本地化字符串。
        /// </summary>
        internal static string openTomlDescription {
            get {
                return ResourceManager.GetString("openTomlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search SerialPort succeed! 的本地化字符串。
        /// </summary>
        internal static string overSerichSP {
            get {
                return ResourceManager.GetString("overSerichSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Even 的本地化字符串。
        /// </summary>
        internal static string parityEven {
            get {
                return ResourceManager.GetString("parityEven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parity 的本地化字符串。
        /// </summary>
        internal static string parityl {
            get {
                return ResourceManager.GetString("parityl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mark 的本地化字符串。
        /// </summary>
        internal static string parityMark {
            get {
                return ResourceManager.GetString("parityMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        internal static string parityNone {
            get {
                return ResourceManager.GetString("parityNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Odd 的本地化字符串。
        /// </summary>
        internal static string parityOdd {
            get {
                return ResourceManager.GetString("parityOdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Space 的本地化字符串。
        /// </summary>
        internal static string paritySpace {
            get {
                return ResourceManager.GetString("paritySpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hex reception 的本地化字符串。
        /// </summary>
        internal static string rxHexl {
            get {
                return ResourceManager.GetString("rxHexl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Serial Plotter 的本地化字符串。
        /// </summary>
        internal static string serialPlotter {
            get {
                return ResourceManager.GetString("serialPlotter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Serial Port 的本地化字符串。
        /// </summary>
        internal static string serialPort {
            get {
                return ResourceManager.GetString("serialPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Serial Port 的本地化字符串。
        /// </summary>
        internal static string serialPortl {
            get {
                return ResourceManager.GetString("serialPortl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Personalize the background. 的本地化字符串。
        /// </summary>
        internal static string softToolBackground {
            get {
                return ResourceManager.GetString("softToolBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Application Background Material 的本地化字符串。
        /// </summary>
        internal static string softTranslucentToolBackground {
            get {
                return ResourceManager.GetString("softTranslucentToolBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 is close 的本地化字符串。
        /// </summary>
        internal static string spClose {
            get {
                return ResourceManager.GetString("spClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 is open 的本地化字符串。
        /// </summary>
        internal static string spConnect {
            get {
                return ResourceManager.GetString("spConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 is plug in 的本地化字符串。
        /// </summary>
        internal static string spPlogin {
            get {
                return ResourceManager.GetString("spPlogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 is pull out 的本地化字符串。
        /// </summary>
        internal static string spPullout {
            get {
                return ResourceManager.GetString("spPullout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Serial Port Settings 的本地化字符串。
        /// </summary>
        internal static string spSettings {
            get {
                return ResourceManager.GetString("spSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start search SerialPort... 的本地化字符串。
        /// </summary>
        internal static string startSerichSP {
            get {
                return ResourceManager.GetString("startSerichSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop bits 的本地化字符串。
        /// </summary>
        internal static string stopBits {
            get {
                return ResourceManager.GetString("stopBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        internal static string stopNone {
            get {
                return ResourceManager.GetString("stopNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1 的本地化字符串。
        /// </summary>
        internal static string stopOne {
            get {
                return ResourceManager.GetString("stopOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1.5 的本地化字符串。
        /// </summary>
        internal static string stopOnePointFive {
            get {
                return ResourceManager.GetString("stopOnePointFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2 的本地化字符串。
        /// </summary>
        internal static string stopTwo {
            get {
                return ResourceManager.GetString("stopTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Thin 的本地化字符串。
        /// </summary>
        internal static string thin {
            get {
                return ResourceManager.GetString("thin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set the background of FSGravityTool to be translucent 的本地化字符串。
        /// </summary>
        internal static string TranslucentBackgroundDescription {
            get {
                return ResourceManager.GetString("TranslucentBackgroundDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transparent 的本地化字符串。
        /// </summary>
        internal static string transparent {
            get {
                return ResourceManager.GetString("transparent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ERROR\r\nThe input is not a hexadecimal number! 的本地化字符串。
        /// </summary>
        internal static string txHexErr {
            get {
                return ResourceManager.GetString("txHexErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hex sending 的本地化字符串。
        /// </summary>
        internal static string txHexl {
            get {
                return ResourceManager.GetString("txHexl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TX 的本地化字符串。
        /// </summary>
        internal static string txl {
            get {
                return ResourceManager.GetString("txl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tx Line Feed 的本地化字符串。
        /// </summary>
        internal static string txNewLinel {
            get {
                return ResourceManager.GetString("txNewLinel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ERROR\r\nSerial port character write error! 的本地化字符串。
        /// </summary>
        internal static string txStringErr {
            get {
                return ResourceManager.GetString("txStringErr", resourceCulture);
            }
        }
    }
}
