//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSGaryityTool_Win11.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FSGaryityTool_Win11.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] BadgeLogo_scale_100 {
            get {
                object obj = ResourceManager.GetObject("BadgeLogo.scale-100", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] BadgeLogo_scale_125 {
            get {
                object obj = ResourceManager.GetObject("BadgeLogo.scale-125", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] BadgeLogo_scale_150 {
            get {
                object obj = ResourceManager.GetObject("BadgeLogo.scale-150", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] BadgeLogo_scale_200 {
            get {
                object obj = ResourceManager.GetObject("BadgeLogo.scale-200", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] BadgeLogo_scale_400 {
            get {
                object obj = ResourceManager.GetObject("BadgeLogo.scale-400", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] FSSoft {
            get {
                object obj = ResourceManager.GetObject("FSSoft", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] FSSoftH {
            get {
                object obj = ResourceManager.GetObject("FSSoftH", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] LargeTile_scale_100 {
            get {
                object obj = ResourceManager.GetObject("LargeTile.scale-100", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] LargeTile_scale_125 {
            get {
                object obj = ResourceManager.GetObject("LargeTile.scale-125", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] LargeTile_scale_150 {
            get {
                object obj = ResourceManager.GetObject("LargeTile.scale-150", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] LargeTile_scale_200 {
            get {
                object obj = ResourceManager.GetObject("LargeTile.scale-200", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] LargeTile_scale_400 {
            get {
                object obj = ResourceManager.GetObject("LargeTile.scale-400", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] LockScreenLogo_scale_200 {
            get {
                object obj = ResourceManager.GetObject("LockScreenLogo.scale-200", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] SmallTile_scale_100 {
            get {
                object obj = ResourceManager.GetObject("SmallTile.scale-100", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] SmallTile_scale_125 {
            get {
                object obj = ResourceManager.GetObject("SmallTile.scale-125", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] SmallTile_scale_150 {
            get {
                object obj = ResourceManager.GetObject("SmallTile.scale-150", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] SmallTile_scale_200 {
            get {
                object obj = ResourceManager.GetObject("SmallTile.scale-200", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] SmallTile_scale_400 {
            get {
                object obj = ResourceManager.GetObject("SmallTile.scale-400", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] SplashScreen_scale_100 {
            get {
                object obj = ResourceManager.GetObject("SplashScreen.scale-100", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] SplashScreen_scale_125 {
            get {
                object obj = ResourceManager.GetObject("SplashScreen.scale-125", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] SplashScreen_scale_150 {
            get {
                object obj = ResourceManager.GetObject("SplashScreen.scale-150", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] SplashScreen_scale_200 {
            get {
                object obj = ResourceManager.GetObject("SplashScreen.scale-200", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] SplashScreen_scale_400 {
            get {
                object obj = ResourceManager.GetObject("SplashScreen.scale-400", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Square150x150Logo_scale_100 {
            get {
                object obj = ResourceManager.GetObject("Square150x150Logo.scale-100", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Square150x150Logo_scale_125 {
            get {
                object obj = ResourceManager.GetObject("Square150x150Logo.scale-125", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Square150x150Logo_scale_150 {
            get {
                object obj = ResourceManager.GetObject("Square150x150Logo.scale-150", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Square150x150Logo_scale_200 {
            get {
                object obj = ResourceManager.GetObject("Square150x150Logo.scale-200", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Square150x150Logo_scale_400 {
            get {
                object obj = ResourceManager.GetObject("Square150x150Logo.scale-400", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Square44x44Logo_altform_lightunplated_targetsize_16 {
            get {
                object obj = ResourceManager.GetObject("Square44x44Logo.altform-lightunplated_targetsize-16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Square44x44Logo_altform_lightunplated_targetsize_24 {
            get {
                object obj = ResourceManager.GetObject("Square44x44Logo.altform-lightunplated_targetsize-24", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Square44x44Logo_altform_lightunplated_targetsize_256 {
            get {
                object obj = ResourceManager.GetObject("Square44x44Logo.altform-lightunplated_targetsize-256", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Square44x44Logo_altform_lightunplated_targetsize_32 {
            get {
                object obj = ResourceManager.GetObject("Square44x44Logo.altform-lightunplated_targetsize-32", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Square44x44Logo_altform_lightunplated_targetsize_48 {
            get {
                object obj = ResourceManager.GetObject("Square44x44Logo.altform-lightunplated_targetsize-48", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Square44x44Logo_altform_unplated_targetsize_16 {
            get {
                object obj = ResourceManager.GetObject("Square44x44Logo.altform-unplated_targetsize-16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Square44x44Logo_altform_unplated_targetsize_256 {
            get {
                object obj = ResourceManager.GetObject("Square44x44Logo.altform-unplated_targetsize-256", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Square44x44Logo_altform_unplated_targetsize_32 {
            get {
                object obj = ResourceManager.GetObject("Square44x44Logo.altform-unplated_targetsize-32", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Square44x44Logo_altform_unplated_targetsize_48 {
            get {
                object obj = ResourceManager.GetObject("Square44x44Logo.altform-unplated_targetsize-48", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Square44x44Logo_scale_100 {
            get {
                object obj = ResourceManager.GetObject("Square44x44Logo.scale-100", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Square44x44Logo_scale_125 {
            get {
                object obj = ResourceManager.GetObject("Square44x44Logo.scale-125", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Square44x44Logo_scale_150 {
            get {
                object obj = ResourceManager.GetObject("Square44x44Logo.scale-150", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Square44x44Logo_scale_200 {
            get {
                object obj = ResourceManager.GetObject("Square44x44Logo.scale-200", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Square44x44Logo_scale_400 {
            get {
                object obj = ResourceManager.GetObject("Square44x44Logo.scale-400", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Square44x44Logo_targetsize_16 {
            get {
                object obj = ResourceManager.GetObject("Square44x44Logo.targetsize-16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Square44x44Logo_targetsize_24 {
            get {
                object obj = ResourceManager.GetObject("Square44x44Logo.targetsize-24", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Square44x44Logo_targetsize_24_altform_unplated {
            get {
                object obj = ResourceManager.GetObject("Square44x44Logo.targetsize-24_altform-unplated", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Square44x44Logo_targetsize_256 {
            get {
                object obj = ResourceManager.GetObject("Square44x44Logo.targetsize-256", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Square44x44Logo_targetsize_32 {
            get {
                object obj = ResourceManager.GetObject("Square44x44Logo.targetsize-32", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Square44x44Logo_targetsize_48 {
            get {
                object obj = ResourceManager.GetObject("Square44x44Logo.targetsize-48", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] StoreLogo {
            get {
                object obj = ResourceManager.GetObject("StoreLogo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] StoreLogo_backup {
            get {
                object obj = ResourceManager.GetObject("StoreLogo.backup", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] StoreLogo_scale_100 {
            get {
                object obj = ResourceManager.GetObject("StoreLogo.scale-100", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] StoreLogo_scale_125 {
            get {
                object obj = ResourceManager.GetObject("StoreLogo.scale-125", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] StoreLogo_scale_150 {
            get {
                object obj = ResourceManager.GetObject("StoreLogo.scale-150", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] StoreLogo_scale_200 {
            get {
                object obj = ResourceManager.GetObject("StoreLogo.scale-200", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] StoreLogo_scale_400 {
            get {
                object obj = ResourceManager.GetObject("StoreLogo.scale-400", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Wide310x150Logo_scale_100 {
            get {
                object obj = ResourceManager.GetObject("Wide310x150Logo.scale-100", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Wide310x150Logo_scale_125 {
            get {
                object obj = ResourceManager.GetObject("Wide310x150Logo.scale-125", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Wide310x150Logo_scale_150 {
            get {
                object obj = ResourceManager.GetObject("Wide310x150Logo.scale-150", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Wide310x150Logo_scale_200 {
            get {
                object obj = ResourceManager.GetObject("Wide310x150Logo.scale-200", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Wide310x150Logo_scale_400 {
            get {
                object obj = ResourceManager.GetObject("Wide310x150Logo.scale-400", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
